Aula05/Models/ErrorViewModel.cs
namespace Aula05.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Aula05/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo;
using Repository;


namespace Aula05.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IWebHostEnvironment environment;

        private CustomerRepository _customerRepository;

        public CustomerController(IWebHostEnvironment environment)
        {
            _customerRepository = new CustomerRepository();
            this.environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Customer> customers = _customerRepository.RetrieveAll();

            return View(customers);
        }

        [HttpPost]
        public IActionResult Create(Customer c)
        {
            _customerRepository.Save(c);
            List<Customer> customers = _customerRepository.RetrieveAll();

            return View("Index", customers);
        }

        [HttpPost]
        public IActionResult Update()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ExportDelimitatedFile()
        {
            string fileContent = string.Empty;
            foreach(Customer c in CustomerData.Customers)
            {
                fileContent += 
                    $"{c.Id};\n{c.Name};\n{c.HomeAddress.Id};\n{ c.HomeAddress.City};\n{c.HomeAddress.StateProvince};\n{c.HomeAddress.Country};\n{c.HomeAddress.StreetLine1};\n{c.HomeAddress.StreetLine2};\n{c.HomeAddress.PostalCode};\n{c.HomeAddress.AddressType};";
            }

            SaveFile(fileContent, "DelimitatedFile.txt");
            
            return View();
        }

        [HttpGet]
        public IActionResult ExportFixedFile()
        {
            string fileContent = string.Empty;
            foreach (Customer c in CustomerData.Customers)
            {
                fileContent +=
                    String.Format("{0:5}", c.Id) +
                    String.Format("{0:64}", c.Name) +
                    String.Format("{0:5}", c.HomeAddress!.Id) +
                    String.Format("{0:32}", c.HomeAddress!.City) +
                    String.Format("{0:2}", c.HomeAddress!.StateProvince) +
                    String.Format("{0:32}", c.HomeAddress!.Country) +
                    String.Format("{0:64}", c.HomeAddress!.StreetLine1) +
                    String.Format("{0:64}", c.HomeAddress!.StreetLine2) +
                    String.Format("{0:9}", c.HomeAddress!.PostalCode) +
                    String.Format("{0:16}", c.HomeAddress!.AddressType) +
                    "\n";
            }
            SaveFile(fileContent, "FixedFile.txt");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is null || id.Value <= 0)
                return NotFound();

            Customer customer = _customerRepository.Retrieve(id.Value);

            if (customer == null)
                return NotFound();

            return View(customer);
        }
        [HttpPost]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id is null || id.Value <= 0)
                return NotFound();

            if (!_customerRepository.DeleteById(id.Value))
                return NotFound();

            return RedirectToAction("Index");
        }

        private bool SaveFile(string content, string fileName)
        {
            bool ret = true;

            if (string.IsNullOrEmpty(content) || string.IsNullOrEmpty(fileName))
                return false;

            var path = Path.Combine(
                environment.WebRootPath,
                "TextFiles"
            );

            try
            {
                if (!System.IO.Directory.Exists(path))
                    System.IO.Directory.CreateDirectory(path);

                var filepath = Path.Combine(
                    environment.WebRootPath,
                    path,
                    fileName
                );

                if (!System.IO.File.Exists(filepath))
                {
                    using (StreamWriter sw = System.IO.File.CreateText(filepath))
                    {
                        sw.Write(content);
                    }

                }
            }
            catch (IOException ioEx)
            {
                string msg = ioEx.Message;
                ret = false;
                //throw ioEx;

            }
            catch (Exception ex)
            {
                string msg = ex.Message;
                ret = false;
            }
            return ret;
        }
    }
}

Aula05/Controllers/HomeController.cs
using System.Diagnostics;
using Aula05.Models;
using Microsoft.AspNetCore.Mvc;
using Modelo;

namespace Aula05.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        // private Order _order;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Customer c1 = new Customer();
            c1.Name = "Frodo";
            c1.ObjectCount++;
            Customer.InstanceCount++;

            var c2 = new Customer();
            c2.Name = "Galadriel";
            c2.ObjectCount++;
            Customer.InstanceCount++;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Aula05/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo;
using Repository;

namespace Aula05.Controllers
{
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment environment;

        private ProductRepository _productRepository;

        public ProductController(IWebHostEnvironment environment)
        {
            ProductRepository _productRepository = new();
            this.environment = environment;
        }

        public ProductController()
        {
            _productRepository = new ProductRepository();
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Product> products = _productRepository.RetrieveAll();

            return View(products);
        }

        [HttpPost]
        public IActionResult Create(Product c)
        {
            _productRepository.Save(c);
            List<Product> products = _productRepository.RetrieveAll();

            return View("Index", products);
        }

        [HttpPost]
        public IActionResult Update()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ExportDelimitedFile()
        {
            /*string filecontent = string.Empty;
            foreach (Product c in ProductData.Products)
            {
                filecontent += $"{c.Id};\n{c.ProductName};\n{c.Description};\n{c.CurrentPrice};\n";
            }

            var path = Path.Combine(
                environment.WebRootPath,
                "TextFiles2"
            );

            if (!System.IO.Directory.Exists(path))
                System.IO.Directory.CreateDirectory(path);

            var filepath = Path.Combine(
                environment.WebRootPath,
                path,
                "Delimitado2.txt"
            );

            if (!System.IO.File.Exists(filepath))
            {
                using (StreamWriter sw = System.IO.File.CreateText(filepath))
                {
                    sw.Write(filepath);
                }

            }
            */
            return View();
        }
    }
}

Aula05/Views/Customer/Create.cshtml
@model Modelo.Customer;

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Cadastro de Consumidor</h1>

    <div class="container">
        <form id="formCustomer" method="post" asp-action="Create" asp-controller="Customer">
            <div class="row">
                <div class="form-group">
                    <label asp-for="@Model.Name">Nome:</label>
                    <input type="text" class="form-control" asp-for="@Model.Name" />
                </div>
            </div>



            <button id="btnCustomer" type="submit" class="btn btn-primary" value="Cadastrar">Cadastrar</button>
        </form>

    </div>
</div>

Aula05/Views/Customer/Delete.cshtml
@model Modelo.Customer

<div class="container">

    <div class="row">
        <div class="col-6">
            Nome:
        </div>
        
        <div class="col-6">
            @Model.Name
        </div>
        
    </div>

    <div class="row">
        <div class="col-6">
            Id:
        </div>

        <div class="col-6">
            @Model.Id
        </div>

    </div>

    <div class="row">

        <div class="col-12">
            <form method="post" asp-action="ConfirmDelete"
                  asp-controller="Customer">
                <input type="hidden" name="id"
                       value="@Model.Id" />
                <button class="btn btn-primary">
                    Excluir
                </button>

                <a asp-action="Index" class="btn btn-danger"
                   asp-controller="Customer">
                    Voltar
                </a>
            </form>
                
            
        </div>

        
    </div>
      
</div>

Aula05/Views/Customer/ExportDelimitatedFile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Aula05/Views/Customer/Index.cshtml
@model List<Modelo.Customer>

<a asp-action="Create" asp-controller="Customer" class="btn btn-light">Novo Customer</a>

@if (Model.Count > 0)
{
    <table class="table table-striped table-bordered table-hover"> 
        <thead class="table-dark">
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
           @foreach (Modelo.Customer customer in Model)
           {
                <tr>
                    <td>@customer.Id</td>
                    <td>@customer.Name</td>
                    <td>
                        <a asp-action="Delete" asp-controller="Customer"
                        asp-route-id="@customer.Id"
                        title="Excluir Customer @customer.Name">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                        
                        
                </tr>           
           }
        </tbody>
    </table>
}
else
{
    <div>
        Não existem registros de customers
    </div>
}

<a asp-action="ExportDelimitatedFile" asp-controller="Customer" class="btn btn-light">Exportar Dados</a>

<a asp-action="ExportFixedFile" 
    asp-controller="Customer" class="btn btn-light"> 
   Exportar dados fixos
</a>

Aula05/Views/Customer/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Aula05/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Aula05/Views/Product/Create.cshtml
@model Modelo.Product

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Cadastro de Produtos</h1>

    <div class="container">
        <form id="formProduct" method="post" asp-action="Create" asp-controller="Product">
            <div class="row">
                <div class="form-group">
                    <label asp-for="@Model.ProductName">Nome do produto:</label>
                    <input type="text" class="form-control" asp-for="@Model.ProductName" />
                </div>
            </div>



            <button id="btnProduct" type="submit" class="btn btn-primary" value="Cadastrar">Cadastrar</button>
        </form>

    </div>
</div>

Aula05/Views/Product/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Aula05/Views/Product/ExportDelimitedFile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Aula05/Views/Product/Index.cshtml
@model List<Modelo.Product>

<a asp-action="Create" asp-controller="Product" class="btn btn-light">Novo Product</a>

@if (Model.Count > 0)
{
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Modelo.Product product in Model)
            {
                <tr>
                    <td>@product.Id</td>
                    <td>@product.ProductName</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div>
        Não existem registros de products
    </div>
}

Aula05/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aula05</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/regular.min.css" integrity="sha512-8hM9a+2hrLBhOuB3uiy+QIXBsu6Qk+snsP1CboFQW6pdt/yYz0IcDp/+CGv5m39r9doGUc/zw6aBpyLF6XFgzg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aula05.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aula05</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Aula05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>